name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3 ]
        laravel: [ 10 ]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, gd
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer install

      - name: Run Tests
        run: vendor/bin/phpunit tests

    services:
      ncanode:
        image: malikzh/ncanode
        env:
          NCANODE_CRL_URL: http://test.pki.gov.kz/crl/nca_gost2022_test.crl
          NCANODE_CA_URL: "http://test.pki.gov.kz/cert/nca_gost2022_test.cer http://test.pki.gov.kz/cert/root_test_gost_2022.cer"
          NCANODE_OCSP_URL: http://test.pki.gov.kz/ocsp/
          NCANODE_TSP_URL: http://test.pki.gov.kz/tsp/
        ports:
          - 14579:14579
        options: --health-cmd="wget -O - http://127.0.0.1:14579/actuator/health | grep -v DOWN || exit 1" --health-interval=20s --health-timeout=30s --health-retries=7

  stub-tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        stack: [ kalkan ]
        laravel: [ 10 ]

    name: Test Stubs - Laravel ${{ matrix.laravel }} - ${{ matrix.stack }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, gd
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:^${{ matrix.laravel }} .
          composer require mitwork/kalkan:@dev --no-interaction --no-update
          composer config repositories.kalkan '{"type": "path", "url": "kalkan"}' --file composer.json
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: 'kalkan'

      - name: Install Kalkan
        run: |
          composer update "mitwork/kalkan" --prefer-dist --no-interaction --no-progress -W

      - name: Install NPM dependencies
        run: npm i

      - name: Compile assets
        run: npm run build

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
